### PR TITLE
Updated Spanish Translation

### PR DESCRIPTION
**Pull request by Johny9505**
Hello. I made some changes to the Spanish translation which consists mostly of minor things like accentuation. I also fixed the translations for "male" and "female." When referring to a person's gender, it is more appropriate to use "macho" and "hembra" for male and female respectively. The use of "sexo" to describe an individual's gender is also more desirable. Also fixed the "Are you sure you want to quit?" prompt as well as the test_character_follow and wait dialogues. I double checked to see if I am using correct grammar but feel free to have someone check on it. I hope this helps and good luck with your project. I look forward to seeing it evolve into something awesome! :)

### CODE REVIEW

**Comment by SaracenOne** [comment]
Ah, thank you for this! :)

**Comment by Johny9505** [comment]
Not a problem! I'm happy I can contribute to this game in one way or another. Te deseo buena suerte y mucho éxito en tu video juego! That's Spanish for "I wish you good luck and great success on your video game" :) 

```
On Friday, April 29, 2016 6:01 PM, SaracenOne <notifications@github.com> wrote:
```

 Ah, thank you for this! :)—

**Comment by SaracenOne** [comment]
Sure thing. Actually, you might be interested to know, but just a few hours ago a commit was pushed to the main engine branch for dynamic fonts, which should help a fair bit with regards to implementing localization support (although moreso for CJK languages specifically).

**Comment by Johny9505** [comment]
Ooohhh Cool. It is good to know the game is progressing smoothly :)
Unfortunately my coding skills are insufficient for core work. As a matter of fact I am still a novice at coding and in game design in general, so I am limited to small commits like language translation haha. I admire the true wizards behinds the scenes though. I find it fascinating how a person can put something together through math and logic and come out with something awesome. And someday I would like to be able to do something like that. However I'm happy providing some feedback and insight, more as a thank you to you game designers for putting so much time and effort into the creation of something wonderful and for the enjoyment for the masses. So really, thank you :)
I will be studying game design with godot though. It is a truly fascinating piece of software which happens to be free with MIT liscence. It will make for a great learning experience! :D 

```
On Monday, May 2, 2016 12:51 AM, SaracenOne <notifications@github.com> wrote:
```

 Sure thing. Actually, you might be interested to know, but just a few hours ago a commit was pushed to the main engine branch for dynamic fonts, which should help a fair bit with regards to implementing localization support (although moreso for CJK languages specifically).—

**Pull request merged**
